kind: pipeline
name: default

clone:
  disable: true

steps:
  - name: clone
    image: plugins/git
    settings:
      depth: 0
      tags: true

  - name: dependencies
    image: docker.io/bitpoke/build:v0.7.4
    commands:
      - composer install --prefer-dist

  - name: lint
    image: docker.io/bitpoke/build:v0.7.4
    commands:
      - make lint
    when:
      event: [push, pull_request]

  - name: test
    image: docker.io/bitpoke/build:v0.7.4
    user: root
    environment:
      DB_TEST_HOST: database
      DB_TEST_NAME: wordpress_tests
      DB_TEST_PASSWORD: not-so-secure-but-good-for-ci
      DB_TEST_USER: wordpress
      MEMCACHED_TEST_HOST: memcache:11211
    commands:
      - make test-runtime
    when:
      event: [push, pull_request]

  - name: integration test
    image: docker.io/bitpoke/build:v0.7.4
    user: root
    environment:
      DB_TEST_HOST: database
      DB_TEST_NAME: wordpress_tests
      DB_TEST_PASSWORD: not-so-secure-but-good-for-ci
      DB_TEST_USER: wordpress
      MEMCACHED_TEST_HOST: memcache:11211
    commands:
      - make test-wp
    when:
      event: [push, pull_request]

  - name: bundle
    pull: always
    image: docker.io/bitpoke/build:v0.7.4
    user: root
    commands:
      - make bundle
    when:
      event: tag

  - name: publish
    image: plugins/github-release@sha256:78bf13eda852e815310a5c4faf3ad04fd0c1c07bf661b4f979ab296f044f9cbd
    settings:
      api_key:
        from_secret: GH_TOKEN
      files:
        - dist/*
      checksum:
        - md5
        - sha1
        - sha512
    when:
      event: tag

services:
  - name: database
    image: percona:5.7
    environment:
      MYSQL_DATABASE: wordpress_tests
      MYSQL_PASSWORD: not-so-secure-but-good-for-ci
      MYSQL_ROOT_PASSWORD: insecure-root-password-but-good-for-ci
      MYSQL_USER: wordpress
    when:
      event: [push, pull_request]

  - name: memcache
    image: memcached:1.5.10-alpine
    when:
      event: [push, pull_request]
