kind: pipeline
name: php-7.3

clone:
  tags: true

steps:
  - name: test
    image: quay.io/presslabs/php-runtime:7.3.7
    user: root
    commands:
    - composer install --no-ansi --prefer-dist
    - make lint
    - make test
      #- make test ARGS="--stop-on-failure"
    environment:
      DB_TEST_HOST: database
      DB_TEST_NAME: wordpress_tests
      DB_TEST_PASSWORD: not-so-secure-but-good-for-ci
      DB_TEST_USER: wordpress
      MEMCACHED_TEST_HOST: memcache:11211
      UPLOADS_FTP_TEST_HOST: ftp:2121
    when:
      event:
      - push

  - name: bundle
    pull: always
    image: quay.io/presslabs/bfc
    user: root
    commands:
      - make bundle
    when:
      event: tag

  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: GH_TOKEN
      files:
        - dist/*
      checksum:
        - md5
        - sha1
        - sha512
    when:
      event: tag

services:
  - name: database
    image: percona:5.7
    environment:
      MYSQL_DATABASE: wordpress_tests
      MYSQL_PASSWORD: not-so-secure-but-good-for-ci
      MYSQL_ROOT_PASSWORD: insecure-root-password-but-good-for-ci
      MYSQL_USER: wordpress

  - name: memcache
    image: memcached:1.5.10-alpine

  - name: ftp
    image: quay.io/presslabs/rclone
    command: ["serve", "ftp", "/", "--addr=0.0.0.0:2121"]
