#!/bin/bash
#
# Copyright 2019 Pressinfra SRL
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e
set -o pipefail


VER="v${1#"v"}"
if [ -z "$1" ] ; then
    echo "release version" >&2
    exit 1
fi

if [ -n "$(git status --porcelain load.php)" ] ; then
    echo "Please commit load.php before doing a release!"
    exit 1
fi

CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
RELEASE_BRANCH="release-${VER}"
cleanup() {
    git checkout "${CURRENT_BRANCH}"
    git branch -D "${RELEASE_BRANCH}"
}
trap cleanup EXIT

set -x
git checkout -b "${RELEASE_BRANCH}"
sed "s/Version: .*$/Version: ${VER}/" load.php > .load.php
mv .load.php load.php
git add load.php
git commit -m "Release ${VER}"
git tag -s -m "Release ${VER}" ${VER}
git push --tags
